<a href="https://colab.research.google.com/github/MartinZuniga178166/MartinZuniga_MineriaDatos/blob/main/Mineria_Datos_178166.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Minería de Datos

##Primer parcial

### Introducción

#### Conceptos
La minería de datos es el proceso de extraer información útil a partir de una acumulación de datos, a menudo provenientes de un almacén o de una recopilación de data sets vinculados.

#### Ciencia de datos
Es un campo interdisciplinario que combina programación, estadística y conocimiento del dominio para extraer información valiosa a partir de datos estructurados y no estructurados.

#### Análisis Estadístico
Es la ciencia de recopilar, explorar y presentar grandes cantidades de datos para descubrir patrones y tendencias implícitas. Es el componente "científico" que permite pasar de tener simples números a poseer evidencia sólida para tomar decisiones.

#### Cuadros y gráficas estadísticos
Los cuadros y gráficas estadísticos son herramientas visuales y organizativas que permiten resumir los datos para que sean fáciles de interpretar. Mientras que los cuadros organizan la información de manera precisa y numérica, las gráficas permiten identificar tendencias y patrones de un solo vistazo.

### Help and documention in Phyton

In [3]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [4]:
len?

In [5]:
L = [1, 2, 3]
L.insert?

In [6]:
L?

In [7]:
def square(a):
  """Return the square of a."""
  return a ** 2

In [8]:
square?

In [9]:
square??

In [10]:
len??

In [11]:
"""
L.
L.c
L.co
L.cou
L._
from itertools import co
import
import h
"""

'\nL.\nL.c\nL.co\nL.cou\nL._\nfrom itertools import co\nimport\nimport h\n'

In [12]:
*Warning?

In [13]:
str.*find*?

### IPhyton Magic Documents

In [14]:
#%time Sirve para evaluar el desempeño, en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)] #Saca el promedio de cada ciclo

66.3 µs ± 826 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [15]:
#El comando $$timeit sirve para evaluar el desempeño en varias lineas, solo que este abarca varias lineas de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

91.1 µs ± 23.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
%timeit?

In [17]:
%%timeit?

### IPython and Shell Commands

In [18]:
!ls

sample_data


In [19]:
%cd /content/sample_data

/content/sample_data


In [20]:
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [21]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [22]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '30f2a44cb240',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

In [23]:
import numpy as np

In [24]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [25]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [26]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [27]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [28]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### The Basics of NumPy Arrays

In [29]:
import numpy as np

In [30]:
np.random.seed(0)  # La semilla

In [31]:
x1 = np.random.randint(10, size=6)  # One-dimensional array || Genera
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array || 3 renglones y 4 columnas
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [32]:
print("x3 ndim: ", x3.ndim)  #mdim se trae el numero de dimensiones
print("x3 shape:", x3.shape) #
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [33]:
print(x2.dtype) #dtype nos dice el tipo de datos

int64


In [34]:
print("itemsize:", x3.itemsize, "bytes") #1 bit = 8 bits
print("nbytes:", x3.nbytes, "bytes")  #tamaño del elemento por el numero

itemsize: 8 bytes
nbytes: 480 bytes


### Array Indexing: Accessing Single Elements

In [35]:
x1

array([5, 0, 3, 3, 7, 9])

In [36]:
x1[0] #Indicamos el indice del elemento del array

np.int64(5)

In [37]:
x1[4]

np.int64(7)

In [38]:
x1[-1] #nos regresa el ultimo elemento de ndarray

np.int64(9)

In [39]:
x1[-2] #nos regresa el penultimo elemento de ndarray

np.int64(7)

In [40]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [41]:
x2[0, 0]

np.int64(3)

In [42]:
x2[0, 2]

np.int64(2)

In [43]:
x2[1, 3]

np.int64(8)

In [44]:
x2[2, -1]

np.int64(7)

In [45]:
x2[0, 0] = 12 #Asignar un nuevo valor (12) al renglon 0 columna 0
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Estadistica básica

#### Media (Mean)

In [46]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


#### Promedio (Average) y Promedio Ponderado

In [47]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [48]:
#Se le asigna un peso diferente, por eso va cambiando la media
print(promedio) #
print(promedio_ponderado)

3.0
3.6666666666666665


#### Mediana

In [49]:
mediana = np.median(data)

#### Varianza y Desviación Estándar

In [50]:
varianza = np.var(data)
desviacion = np.std(data)  #en la mayoria de casos es la raiz cuadrada de la varianza

### Generación de Datos Aleatorios

In [51]:
muestra = np.random.normal(0, 1, 1000) #media 0, desv std 1 y generar 1000 datos
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


### Correlación

In [52]:
corr = np.corrcoef([1,2,3], [1,5,7])
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

 ### Funciones Estadísticas Adicionales (NumPy)

In [56]:
#Cuantiles
(np.quantile)

#Percentiles
(np.percentile)

#Histogramas
(np.histogram)

#Covarianza
(np.cov)

#Manejo de NaN
(np.nanmean, etc.)

NameError: name 'etc' is not defined

### Cuadros estadisticos

In [ ]:
import numpy as np
import pandas as pd
from io import StringIO

raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

In [ ]:
# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t')
df.columns = [c.strip() for c in df.columns]

In [ ]:
# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

In [ ]:
df.head()

In [ ]:
# A NumPy
edad = df['edad'].to_numpy(dtype=float)
prog_py = df['prog_python'].to_numpy(dtype=bool)
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)

In [ ]:
edad[:5]

In [ ]:
prog_py[:5]

In [ ]:
# Descriptivos de edad (NumPy)
summary_age = {
    'n': int(edad.size),
    'min': float(np.min(edad)),  #Trae la edad minima
    'p25': float(np.percentile(edad, 25)), # genera 25$ de los elementos
    'mediana': float(np.median(edad)), #Ordena datos y seleccionamos elemento de medio si es impar, si es par usa el promedio de los dos de la mitad
    'media': float(np.mean(edad)),
    'p75': float(np.percentile(edad, 75)),
    'max': float(np.max(edad)), #Edad maximo
    'rango(ptp)': float(np.ptp(edad)), #rango de dif mayor menos la menor
    'var_muestral': float(np.var(edad, ddof=1)), #la varianza que hay
    'std_muestral': float(np.std(edad, ddof=1)),
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)),
}

In [ ]:
summary_age

In [ ]:
# Frecuencias (NumPy)
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))} #Asigna llave y cuenta los que no sean cero en programación de python, los true son unos y false ceros
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))}
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}

In [ ]:
print(f'Frecuencia de utilización de python:{freq_python}')
print(f'Frecuencia de utilización de colab:{freq_colab}')
print(f'Frecuencia de utilización de github:{freq_gh}')

In [ ]:
# Tablas cruzadas (NumPy)
def tabla2x2(a, b):
    t = np.zeros((2,2), dtype=int)
    t[1,1] = np.count_nonzero(a & b)
    t[1,0] = np.count_nonzero(a & ~b) # ~=not y & es and
    t[0,1] = np.count_nonzero(~a & b)
    t[0,0] = np.count_nonzero(~a & ~b)
    return t
tab_py_colab = tabla2x2(prog_py, usa_colab)
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)

In [ ]:
print(f'Tabla 2x2 de python y colab:\n{tab_py_colab}')

In [ ]:
print(f'Tabla 2x2 de python y github:\n{tab_py_gh}')

In [ ]:
# Medias de edad por grupo (NumPy)
means_by_group = {
    'edad_promedio_Python': {'Si': float(np.mean(edad[prog_py])) if np.any(prog_py) else np.nan,
                             'No': float(np.mean(edad[~prog_py])) if np.any(~prog_py) else np.nan},
    'edad_promedio_Colab':  {'Si': float(np.mean(edad[usa_colab])) if np.any(usa_colab) else np.nan,
                             'No': float(np.mean(edad[~usa_colab])) if np.any(~usa_colab) else np.nan},
    'edad_promedio_GitHub': {'Si': float(np.mean(edad[cuenta_gh])) if np.any(cuenta_gh) else np.nan,
                             'No': float(np.mean(edad[~cuenta_gh])) if np.any(~cuenta_gh) else np.nan},
}

summary_age, freq_python, freq_colab, freq_gh, tab_py_colab, tab_py_gh, tab_colab_gh, means_by_group

#sustituir por , los \ t del archivo, lo subimos y usamos pandas para scv el parametro nombre archivo

In [ ]:
csv_data = raw.replace("\t", ",")

# Para ver los primeros 200 caracteres del resultado
print(raw)