<a href="https://colab.research.google.com/github/MartinZuniga178166/MartinZuniga_MineriaDatos/blob/main/Mineria_Datos_178166.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Minería de Datos

##Primer parcial

### Introducción

#### Conceptos
La minería de datos es el proceso de extraer información útil a partir de una acumulación de datos, a menudo provenientes de un almacén o de una recopilación de data sets vinculados.

#### Ciencia de datos
Es un campo interdisciplinario que combina programación, estadística y conocimiento del dominio para extraer información valiosa a partir de datos estructurados y no estructurados.

#### Análisis Estadístico
Es la ciencia de recopilar, explorar y presentar grandes cantidades de datos para descubrir patrones y tendencias implícitas. Es el componente "científico" que permite pasar de tener simples números a poseer evidencia sólida para tomar decisiones.

#### Cuadros y gráficas estadísticos
Los cuadros y gráficas estadísticos son herramientas visuales y organizativas que permiten resumir los datos para que sean fáciles de interpretar. Mientras que los cuadros organizan la información de manera precisa y numérica, las gráficas permiten identificar tendencias y patrones de un solo vistazo.

### Help and documention in Phyton

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1, 2, 3]
L.insert?

In [ ]:
L?

In [ ]:
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

In [ ]:
"""
L.
L.c
L.co
L.cou
L._
from itertools import co
import
import h
"""

'\nL.\nL.c\nL.co\nL.cou\nL._\nfrom itertools import co\nimport\nimport h\n'

In [ ]:
*Warning?

In [ ]:
str.*find*?

### IPhyton Magic Documents

In [ ]:
#%time Sirve para evaluar el desempeño, en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)] #Saca el promedio de cada ciclo

141 µs ± 75.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#El comando $$timeit sirve para evaluar el desempeño en varias lineas, solo que este abarca varias lineas de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

73.6 µs ± 710 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

### IPython and Shell Commands

In [ ]:
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [ ]:
%cd /content/sample_data

/content/sample_data


In [ ]:
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [ ]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'b98c3aceaf41',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

In [ ]:
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### The Basics of NumPy Arrays

In [1]:
import numpy as np

In [2]:
np.random.seed(0)  # La semilla

In [3]:
x1 = np.random.randint(10, size=6)  # One-dimensional array || Genera
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array || 3 renglones y 4 columnas
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [4]:
print("x3 ndim: ", x3.ndim)  #mdim se trae el numero de dimensiones
print("x3 shape:", x3.shape) #
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print(x2.dtype) #dtype nos dice el tipo de datos

int64


In [6]:
print("itemsize:", x3.itemsize, "bytes") #1 bit = 8 bits
print("nbytes:", x3.nbytes, "bytes")  #tamaño del elemento por el numero

itemsize: 8 bytes
nbytes: 480 bytes


### Array Indexing: Accessing Single Elements

In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [8]:
x1[0] #Indicamos el indice del elemento del array

np.int64(5)

In [9]:
x1[4]

np.int64(7)

In [10]:
x1[-1] #nos regresa el ultimo elemento de ndarray

np.int64(9)

In [11]:
x1[-2] #nos regresa el penultimo elemento de ndarray

np.int64(7)

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x2[0, 0]

np.int64(3)

In [14]:
x2[0, 2]

np.int64(2)

In [16]:
x2[1, 3]

np.int64(8)

In [17]:
x2[2, -1]

np.int64(7)

In [18]:
x2[0, 0] = 12 #Asignar un nuevo valor (12) al renglon 0 columna 0
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Estadistica básica

#### Media (Mean)

In [19]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


#### Promedio (Average) y Promedio Ponderado

In [20]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [22]:
#Se le asigna un peso diferente, por eso va cambiando la media
print(promedio) #
print(promedio_ponderado)

3.0
3.6666666666666665


#### Mediana

In [24]:
mediana = np.median(data)

#### Varianza y Desviación Estándar

In [25]:
varianza = np.var(data)
desviacion = np.std(data)  #en la mayoria de casos es la raiz cuadrada de la varianza

### Generación de Datos Aleatorios

In [26]:
muestra = np.random.normal(0, 1, 1000) #media 0, desv std 1 y generar 1000 datos
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


### Correlación

In [30]:
corr = np.corrcoef([1,2,3], [1,5,7])
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

 ### Funciones Estadísticas Adicionales (NumPy)

In [ ]:
#Cuantiles
(np.quantile)

#Percentiles
(np.percentile)

#Histogramas
(np.histogram)

#Covarianza
(np.cov)

#Manejo de NaN
(np.nanmean, etc.)